name: "Terraform Plan"

on:
  pull_request:
    branches: [ "main" ]
    paths: "projects/practice-service/**"

jobs:
  terraform:
    name: "Terraform Plan"
    runs-on: ubuntu-latest
    permissions:
      contents: read #ì½”ë“œë¥¼ ì½ì–´ì˜¬ ìˆ˜ ìˆëŠ” ê¶Œí•œ
      pull-requests: write #PRì— ëŒ“ê¸€ì„ ë‹¬ ìˆ˜ ìˆëŠ” ê¶Œí•œ
    
    steps:
      - name: Checkout 
        uses: actions/checkout@v6

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      
      - name: Format
        run: terraform fmt -check -recursive
        working-directory: projects/practice-service/dev
      
      - name: Init
        run: terraform init
        working-directory: projects/practice-service/dev
      
      - name: Plan
        id: plan
        working-directory: projects/practice-service/dev
        run: terraform plan -no-color

      # 7. PRì— ê²°ê³¼ ëŒ“ê¸€ ë‹¬ê¸°
      - name: Post Plan Comment
        uses: actions/github-script@v7
        if: github.event_name == 'pull_request'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `### Terraform Plan Result
            #### ğŸ“‚ Directory: \`projects/practice-service/dev\`
            #### ğŸ›¡ï¸ Security & Format Check: \`Passed\`
            
            <details><summary>ğŸ” ìƒì„¸ ë³€ê²½ ë‚´ìš© ë³´ê¸° (Click)</summary>
            
            \`\`\`hcl
            ${{ steps.plan.outputs.stdout }}
            \`\`\`
            
            </details>
            
            *Pushed by: @${context.actor}, Action: \`${context.eventName}\`*`;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
